version: '3.8'

services:
  monocle:
    build: .
    container_name: monocle
    ports:
      - "8000:8000"
    volumes:
      - ./test.jpg:/app/test.jpg:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
